### ISSUE TITLE
oomox themes with gnome 3.20, enabling desktop icons remove wallpaper

### ISSUE THREAD

**Issue by terroreek** [actionless/oomox#30]
Hi

When I enable 'icons on desktop' with tweak tool with gnome 3.20, on all oomox themes the wallpaper disappears.

I am running Siduction (Debian Sid), I am not able to reproduce the issue while running Adwaita or the Cloak-3.20 gtk theme, which is why I believe its the oomox theme.

**Comment by actionless** [comment]
can you reproduce it with Numix?

**Comment by terroreek** [comment]
well no I can't but if I try to use the numix theme from github (https://github.com/numixproject/numix-gtk-theme), my gtk windows become transparent with white text.  The wall paper is still working correctly but things like tweak tool are 100% transparent.

**Comment by actionless** [comment]
> however updating oomox fixed that issue. 
so it is working fine now?

**Comment by terroreek** [comment]
Sorry the transparent windows was solved by updating oomox, but the only current issue I am facing with oomox.

**Comment by actionless** [comment]
sorry, it's still not clear:
what the issue do you have now with the latest git master of oomox?

**Comment by terroreek** [comment]
The only issue is when you enable desktop icons via tweak tool the wallpaper disappears.

**Comment by actionless** [comment]
thanks for reporting, i will check

**Comment by megax** [comment]
@actionless Fixed: https://github.com/numixproject/numix-gtk-theme/commit/bd780f03d408f5ff8e7e6851a2572b291d713a95

**Comment by actionless** [comment]
thanks for fixing that!
it's already included in the latest release: https://github.com/actionless/oomox/commit/bd780f03d408f5ff8e7e6851a2572b291d713a95
